import type { DOCUMENT_TYPES } from "@/db/schema/grc";

// Dokument-Vorlagen: deutsche Gerüste für Richtlinien, Verfahren, Konzepte,
// Pläne — je mit Control-Vorverknüpfung (deckt damit quer alle gewählten
// Rahmenwerke ab). `isoMandatory` = Pflichtdokument der ISO 27001 (P).
// Inhalt ist ein Gerüst (Markdown mit Platzhaltern), kein Rechtsrat.

export type DocumentTemplate = {
	code: string;
	title: string;
	type: (typeof DOCUMENT_TYPES)[number];
	domain: string;
	approverFunction:
		| "management_body"
		| "compliance"
		| "isb_ciso"
		| "ict_risk_function"
		| "aml_officer"
		| "dpo";
	reviewCycleMonths: number;
	isoMandatory: boolean;
	controls: string[];
	legalBasisRefs: string[];
	frameworks: string[];
	body: string;
};

const skeleton = (title: string, purpose: string, sections: string[]): string =>
	[
		`# ${title}`,
		"",
		"| Feld | Wert |",
		"|---|---|",
		"| Dokumentnummer | {{docNumber}} |",
		"| Version | {{version}} |",
		"| Eigner:in | {{owner}} |",
		"| Freigabe | {{approver}} |",
		"| Gültig ab | {{effectiveFrom}} |",
		"| Nächster Review | {{nextReviewAt}} |",
		"",
		"## 1. Zweck und Geltungsbereich",
		"",
		purpose,
		"",
		...sections.flatMap((s, i) => [`## ${i + 2}. ${s}`, "", "_…_", ""]),
		"## Rechtsgrundlagen und Controls",
		"",
		"Siehe Verknüpfungen dieses Dokuments (Controls → Anforderungen je Rahmenwerk).",
		"",
	].join("\n");

export const DOCUMENT_TEMPLATES: DocumentTemplate[] = [
	{
		code: "RL-ISMS-LEITLINIE",
		title: "Informationssicherheitsleitlinie",
		type: "policy",
		domain: "governance",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: true,
		controls: ["CC-GOV-01", "CC-GOV-03"],
		legalBasisRefs: [
			"ISO 27001 5.2",
			"DORA Art. 9(4)(a)",
			"NIS2 Art. 21(2)(a)",
		],
		frameworks: ["iso27001", "dora", "nis2"],
		body: skeleton(
			"Informationssicherheitsleitlinie",
			"Diese Leitlinie legt Ziele, Grundsätze und Verantwortung für Informationssicherheit in der Organisation fest.",
			[
				"Sicherheitsziele",
				"Grundsätze",
				"Rollen und Verantwortung",
				"Themenrichtlinien",
				"Verstösse und Ausnahmen",
				"Überprüfung",
			],
		),
	},
	{
		code: "KZ-SCOPE",
		title: "Geltungsbereich des ISMS",
		type: "concept",
		domain: "governance",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: true,
		controls: ["CC-GOV-04"],
		legalBasisRefs: ["ISO 27001 4.3"],
		frameworks: ["iso27001"],
		body: skeleton(
			"Geltungsbereich des ISMS",
			"Festlegung der Grenzen und Anwendbarkeit des Managementsystems inklusive Schnittstellen und Ausschlüssen.",
			[
				"Organisationseinheiten und Standorte",
				"Prozesse und Dienste",
				"Systeme und Schnittstellen",
				"Ausschlüsse mit Begründung",
			],
		),
	},
	{
		code: "KZ-RISIKOMETHODIK",
		title: "Risikobeurteilungsmethodik",
		type: "concept",
		domain: "risk",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: true,
		controls: ["CC-RSK-01"],
		legalBasisRefs: ["ISO 27001 6.1.2", "DORA Art. 6", "NIS2 Art. 21(2)(a)"],
		frameworks: ["iso27001", "dora", "nis2"],
		body: skeleton(
			"Risikobeurteilungsmethodik",
			"Methode, Skalen, Akzeptanzkriterien und Zuständigkeiten für die Beurteilung und Behandlung von Informationssicherheits- und IKT-Risiken.",
			[
				"Skalen (Eintrittswahrscheinlichkeit, Auswirkung)",
				"Risikoappetit und Akzeptanzkriterien",
				"Identifikation und Bewertung",
				"Behandlungsoptionen",
				"Review-Zyklus",
			],
		),
	},
	{
		code: "BE-SOA",
		title: "Erklärung zur Anwendbarkeit (SoA)",
		type: "record",
		domain: "risk",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: true,
		controls: ["CC-RSK-03"],
		legalBasisRefs: ["ISO 27001 6.1.3 d)"],
		frameworks: ["iso27001"],
		body: skeleton(
			"Erklärung zur Anwendbarkeit",
			"Welche Controls gewählt oder ausgeschlossen sind und warum — generiert aus /rahmenwerke/iso27001?tab=soa.",
			["Vorgehen", "Ausschlüsse", "Verweis auf Controls"],
		),
	},
	{
		code: "PL-RISIKOBEHANDLUNG",
		title: "Risikobehandlungsplan",
		type: "plan",
		domain: "risk",
		approverFunction: "management_body",
		reviewCycleMonths: 6,
		isoMandatory: true,
		controls: ["CC-RSK-03"],
		legalBasisRefs: ["ISO 27001 6.1.3 e)"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Risikobehandlungsplan",
			"Massnahmen, Verantwortliche und Termine zur Behandlung der identifizierten Risiken.",
			[
				"Priorisierte Massnahmen",
				"Verantwortliche und Termine",
				"Restrisiko und Akzeptanz",
			],
		),
	},
	{
		code: "KZ-ZIELE",
		title: "Sicherheitsziele und Kennzahlen",
		type: "concept",
		domain: "governance",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: true,
		controls: ["CC-GOV-05", "CC-GOV-15"],
		legalBasisRefs: ["ISO 27001 6.2", "DORA Art. 6(8)"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Sicherheitsziele und Kennzahlen",
			"Messbare Ziele des ISMS und der digitalen operationalen Resilienz mit Kennzahlen, Zielwerten und Messverfahren.",
			["Ziele", "Kennzahlen und Zielwerte", "Messung und Berichterstattung"],
		),
	},
	{
		code: "KZ-RESILIENZSTRATEGIE",
		title: "Strategie für digitale operationale Resilienz",
		type: "concept",
		domain: "governance",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-GOV-15"],
		legalBasisRefs: ["DORA Art. 6(8)"],
		frameworks: ["dora"],
		body: skeleton(
			"Strategie für digitale operationale Resilienz",
			"Toleranzschwellen, Ziele, Zielarchitektur, Kennzahlen und Umgang mit IKT-Drittparteien.",
			[
				"Toleranzschwellen für IKT-Störungen",
				"Resilienzziele",
				"Zielarchitektur",
				"Drittparteien-Strategie",
				"Kennzahlen und Überprüfung",
			],
		),
	},
	{
		code: "KZ-IKT-RISIKORAHMEN",
		title: "IKT-Risikomanagementrahmen",
		type: "concept",
		domain: "risk",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-RSK-01", "CC-GOV-19", "CC-RSK-04"],
		legalBasisRefs: ["DORA Art. 6", "RTS 2024/1774"],
		frameworks: ["dora"],
		body: skeleton(
			"IKT-Risikomanagementrahmen",
			"Strategien, Leitlinien, Verfahren und Werkzeuge zum Schutz aller IKT-Assets; drei Verteidigungslinien; jährliche Überprüfung.",
			[
				"Governance und Kontrollfunktion",
				"Identifikation und Klassifizierung",
				"Schutz und Prävention",
				"Erkennung",
				"Reaktion und Wiederherstellung",
				"Lernen und Kommunikation",
				"Überprüfung",
			],
		),
	},
	{
		code: "RL-ZUGANG",
		title: "Zugangs- und Berechtigungsrichtlinie",
		type: "policy",
		domain: "access",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: [
			"CC-IAM-01",
			"CC-IAM-02",
			"CC-IAM-03",
			"CC-IAM-04",
			"CC-IAM-05",
			"CC-IAM-08",
		],
		legalBasisRefs: [
			"ISO 27001 A.5.15–A.5.18",
			"DORA Art. 9(4)(c)(d)",
			"NIS2 Art. 21(2)(i)(j)",
		],
		frameworks: ["iso27001", "dora", "nis2"],
		body: skeleton(
			"Zugangs- und Berechtigungsrichtlinie",
			"Need-to-know, Least Privilege, Lebenszyklus von Konten, starke Authentisierung, privilegierte Zugänge, Rezertifizierung.",
			[
				"Grundsätze",
				"Identitätslebenszyklus",
				"Authentisierung (MFA, Passkeys)",
				"Privilegierte Zugänge",
				"Rezertifizierung",
				"Remote-Zugriff",
			],
		),
	},
	{
		code: "KZ-KRYPTO",
		title: "Kryptokonzept",
		type: "concept",
		domain: "crypto",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-CRY-01", "CC-CRY-02", "CC-CRY-03", "CC-CRY-04", "CC-CRY-05"],
		legalBasisRefs: [
			"ISO 27001 A.8.24",
			"DORA Art. 9(2)",
			"NIS2 Art. 21(2)(h)",
			"BSI TR-02102",
		],
		frameworks: ["iso27001", "dora", "nis2"],
		body: skeleton(
			"Kryptokonzept",
			"Zugelassene Verfahren, Schlüssellängen, Einsatzfälle, Schlüsselmanagement und Rotation.",
			[
				"Algorithmen und Schlüssellängen",
				"Einsatzfälle (ruhend, Transport, Felder)",
				"Schlüsselmanagement",
				"Rotation und Kompromittierung",
				"Ausnahmen",
			],
		),
	},
	{
		code: "RL-PATCH",
		title: "Schwachstellen- und Patchmanagement",
		type: "policy",
		domain: "operations",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-OPS-03", "CC-DEV-05"],
		legalBasisRefs: [
			"ISO 27001 A.8.8",
			"DORA Art. 9(4)(f)",
			"NIS2 Art. 21(2)(e)",
		],
		frameworks: ["iso27001", "dora", "nis2"],
		body: skeleton(
			"Schwachstellen- und Patchmanagement",
			"Erkennung, Bewertung, Fristen und Behebung von Schwachstellen; Notfall-Patches.",
			[
				"Quellen und Scans",
				"Bewertung und Fristen (SLA)",
				"Notfall-Patches",
				"Ausnahmen",
				"Berichterstattung",
			],
		),
	},
	{
		code: "RL-NETZ",
		title: "Netzsicherheitsrichtlinie",
		type: "policy",
		domain: "network",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-NET-01", "CC-NET-02", "CC-NET-03"],
		legalBasisRefs: ["ISO 27001 A.8.20–A.8.23", "DORA Art. 9(4)(b)"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Netzsicherheitsrichtlinie",
			"Segmentierung, Perimeterschutz, Fernzugriff, Überwachung des Netzverkehrs.",
			[
				"Segmentierung",
				"Firewall-Regeln und Review",
				"Fernzugriff",
				"Netzdienste",
			],
		),
	},
	{
		code: "RL-CHANGE",
		title: "Änderungsmanagement",
		type: "policy",
		domain: "development",
		approverFunction: "ict_risk_function",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-DEV-06", "CC-GOV-12"],
		legalBasisRefs: ["ISO 27001 A.8.32", "DORA Art. 9(4)(e)", "MaRisk AT 8"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Änderungsmanagement",
			"Beantragung, Bewertung, Test, Freigabe und Dokumentation von Änderungen; Notfall-Changes.",
			[
				"Änderungsarten",
				"Bewertung und Freigabe",
				"Test und Rollback",
				"Notfall-Changes",
				"Dokumentation",
			],
		),
	},
	{
		code: "RL-ENTWICKLUNG",
		title: "Richtlinie sichere Entwicklung",
		type: "policy",
		domain: "development",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-DEV-01", "CC-DEV-02", "CC-DEV-03", "CC-DEV-04", "CC-DEV-07"],
		legalBasisRefs: [
			"ISO 27001 A.8.25–A.8.31",
			"DORA Art. 25",
			"NIS2 Art. 21(2)(e)",
		],
		frameworks: ["iso27001", "dora", "nis2"],
		body: skeleton(
			"Richtlinie sichere Entwicklung",
			"Sicherheit in jeder Phase der Entwicklung: Anforderungen, Design, Code, Test, Deployment.",
			[
				"Sicherheitsanforderungen",
				"Bedrohungsmodellierung",
				"Coding-Standards und Analyse",
				"Tests",
				"Umgebungen und Deployment",
			],
		),
	},
	{
		code: "RL-LOGGING",
		title: "Protokollierungs- und Überwachungskonzept",
		type: "concept",
		domain: "operations",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-LOG-01", "CC-LOG-02", "CC-LOG-03"],
		legalBasisRefs: ["ISO 27001 A.8.15/A.8.16", "DORA Art. 10"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Protokollierungs- und Überwachungskonzept",
			"Was protokolliert wird, wie lange, wie geschützt; Alarme und Reaktion.",
			[
				"Ereignisse",
				"Aufbewahrung und Schutz",
				"Ausschlüsse (Secrets, PII)",
				"Alarme",
				"Auswertung",
			],
		),
	},
	{
		code: "RL-ENDGERAETE",
		title: "Endgeräte- und Mobilgeräterichtlinie",
		type: "policy",
		domain: "operations",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-OPS-01", "CC-OPS-02", "CC-OPS-06", "CC-PHY-04"],
		legalBasisRefs: ["ISO 27001 A.8.1, A.7.9, A.7.10"],
		frameworks: ["iso27001"],
		body: skeleton(
			"Endgeräte- und Mobilgeräterichtlinie",
			"Härtung, Verschlüsselung, Verwaltung und zulässiger Gebrauch von Endgeräten und Speichermedien.",
			[
				"Baseline",
				"Verschlüsselung und Sperre",
				"Software-Installation",
				"Verlust und Diebstahl",
			],
		),
	},
	{
		code: "RL-ASSETS",
		title: "Asset-Management und Klassifizierung",
		type: "policy",
		domain: "asset",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-AST-01", "CC-AST-02", "CC-AST-03", "CC-AST-07"],
		legalBasisRefs: ["ISO 27001 A.5.9–A.5.14", "DORA Art. 8"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Asset-Management und Klassifizierung",
			"Inventar, Verantwortliche, Klassifizierung, Kennzeichnung, zulässiger Gebrauch, Übertragung.",
			[
				"Inventar",
				"Klassifizierungsschema",
				"Handhabung je Klasse",
				"Rückgabe",
			],
		),
	},
	{
		code: "KZ-LOESCHUNG",
		title: "Aufbewahrungs- und Löschkonzept",
		type: "concept",
		domain: "asset",
		approverFunction: "dpo",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-AST-10", "CC-CMP-01"],
		legalBasisRefs: [
			"ISO 27001 A.5.33, A.8.10",
			"DSGVO Art. 5(1)(e), 17",
			"GwG § 8",
			"HGB § 257",
		],
		frameworks: ["iso27001", "dsgvo", "gwg"],
		body: skeleton(
			"Aufbewahrungs- und Löschkonzept",
			"Fristen je Datenkategorie, Löschverfahren, Nachweis; Audit-Log und GwG-Aufzeichnungen ausgenommen.",
			[
				"Datenkategorien und Fristen",
				"Löschverfahren",
				"Nachweis",
				"Ausnahmen",
			],
		),
	},
	{
		code: "RL-DIENSTLEISTER",
		title: "Dienstleister- und Auslagerungsrichtlinie",
		type: "policy",
		domain: "supplier",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: [
			"CC-TPR-01",
			"CC-TPR-02",
			"CC-TPR-03",
			"CC-TPR-04",
			"CC-TPR-05",
			"CC-TPR-06",
			"CC-TPR-07",
			"CC-TPR-08",
		],
		legalBasisRefs: [
			"ISO 27001 A.5.19–A.5.23",
			"DORA Art. 28–30",
			"RTS 2024/1773",
			"NIS2 Art. 21(2)(d)",
			"MaRisk AT 9",
		],
		frameworks: ["iso27001", "dora", "nis2"],
		body: skeleton(
			"Dienstleister- und Auslagerungsrichtlinie",
			"Auswahl, Due Diligence, Vertrag, Überwachung, Konzentration, Exit; Informationsregister.",
			[
				"Strategie",
				"Due Diligence",
				"Pflichtklauseln (Art. 30)",
				"Überwachung",
				"Konzentrationsrisiko und Unterauftrag",
				"Exit",
				"Register und Anzeigen",
			],
		),
	},
	{
		code: "VA-EXIT-PLAN",
		title: "Ausstiegsplan (Vorlage je kritischem Dienstleister)",
		type: "template",
		domain: "supplier",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-TPR-06"],
		legalBasisRefs: ["DORA Art. 28(8)"],
		frameworks: ["dora"],
		body: skeleton(
			"Ausstiegsplan",
			"Alternativen, Datenrückführung, Zeitplan und Test für den Wechsel eines kritischen Dienstleisters.",
			[
				"Auslöser",
				"Alternativen",
				"Datenrückführung und Löschung",
				"Zeitplan",
				"Test",
			],
		),
	},
	{
		code: "RL-VORFALL",
		title: "Vorfall- und Melderichtlinie",
		type: "policy",
		domain: "incident",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: [
			"CC-INC-01",
			"CC-INC-02",
			"CC-INC-03",
			"CC-INC-05",
			"CC-INC-06",
			"CC-INC-07",
		],
		legalBasisRefs: [
			"ISO 27001 A.5.24–A.5.28",
			"DORA Art. 17–23",
			"RTS 2024/1772",
			"NIS2 Art. 23",
			"DSGVO Art. 33",
		],
		frameworks: ["iso27001", "dora", "nis2", "dsgvo"],
		body: skeleton(
			"Vorfall- und Melderichtlinie",
			"Erfassen, Klassifizieren, Reagieren, Melden (DORA, NIS2, DSGVO) und Lernen aus Vorfällen.",
			[
				"Rollen und Meldewege",
				"Klassifizierung",
				"Fristen je Regime",
				"Reaktion und Beweissicherung",
				"Nachbetrachtung",
			],
		),
	},
	{
		code: "PL-KRISENKOMMUNIKATION",
		title: "Krisenkommunikationsplan",
		type: "plan",
		domain: "incident",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-INC-04", "CC-BCM-06", "CC-GOV-09"],
		legalBasisRefs: ["DORA Art. 14", "ISO 27001 7.4"],
		frameworks: ["dora", "iso27001"],
		body: skeleton(
			"Krisenkommunikationsplan",
			"Wer informiert Kunden, Partner, Aufsicht und Öffentlichkeit — mit Vorlagen und Sprecherfunktion.",
			["Krisenstab", "Zielgruppen und Kanäle", "Vorlagen", "Freigaben"],
		),
	},
	{
		code: "RL-BCM",
		title: "Geschäftsfortführungsleitlinie",
		type: "policy",
		domain: "continuity",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-BCM-01", "CC-BCM-02", "CC-BCM-05", "CC-BCM-06"],
		legalBasisRefs: [
			"ISO 27001 A.5.29/A.5.30",
			"DORA Art. 11",
			"NIS2 Art. 21(2)(c)",
			"MaRisk AT 7.3",
		],
		frameworks: ["iso27001", "dora", "nis2"],
		body: skeleton(
			"Geschäftsfortführungsleitlinie",
			"Ziele, BIA, Pläne, Tests und Krisenmanagement zur Sicherung kritischer Funktionen.",
			[
				"Ziele und Geltungsbereich",
				"Business-Impact-Analyse",
				"Pläne",
				"Tests und Übungen",
				"Krisenmanagement",
			],
		),
	},
	{
		code: "PL-NOTFALL",
		title: "Notfall- und Wiederanlaufplan",
		type: "plan",
		domain: "continuity",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-BCM-01", "CC-BCM-03", "CC-BCM-04"],
		legalBasisRefs: ["DORA Art. 11, 12", "ISO 27001 A.5.30"],
		frameworks: ["dora", "iso27001"],
		body: skeleton(
			"Notfall- und Wiederanlaufplan",
			"Szenarien, Wiederanlaufreihenfolge, RTO/RPO, Backup/Restore, Kontakte.",
			[
				"Szenarien",
				"Wiederanlaufreihenfolge",
				"Backup und Wiederherstellung",
				"Kontakte",
				"Rückkehr zum Normalbetrieb",
			],
		),
	},
	{
		code: "KZ-BACKUP",
		title: "Backup-Konzept",
		type: "concept",
		domain: "continuity",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-BCM-03"],
		legalBasisRefs: ["ISO 27001 A.8.13", "DORA Art. 12"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Backup-Konzept",
			"Umfang, Häufigkeit, Verschlüsselung, Standorte, Aufbewahrung, Restore-Tests.",
			[
				"Umfang und Häufigkeit",
				"Verschlüsselung und Standorte",
				"Aufbewahrung",
				"Restore-Tests",
			],
		),
	},
	{
		code: "RL-PERSONAL",
		title: "Personalsicherheit",
		type: "policy",
		domain: "hr",
		approverFunction: "management_body",
		reviewCycleMonths: 24,
		isoMandatory: false,
		controls: ["CC-HR-01", "CC-HR-02", "CC-HR-03", "CC-HR-04"],
		legalBasisRefs: ["ISO 27001 A.6.1–A.6.6", "NIS2 Art. 21(2)(i)"],
		frameworks: ["iso27001", "nis2"],
		body: skeleton(
			"Personalsicherheit",
			"Prüfung vor Einstellung, Vertraulichkeit, Schulung, Disziplinarverfahren, Austritt.",
			[
				"Vor Einstellung",
				"Während der Beschäftigung",
				"Schulung",
				"Verstösse",
				"Austritt",
			],
		),
	},
	{
		code: "PL-SCHULUNG",
		title: "Schulungsplan",
		type: "plan",
		domain: "hr",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-HR-03", "CC-GOV-16"],
		legalBasisRefs: [
			"ISO 27001 7.2/7.3",
			"DORA Art. 5(4), 13(6)",
			"NIS2 Art. 20(2)",
			"GwG § 6 Abs. 2 Nr. 6",
		],
		frameworks: ["iso27001", "dora", "nis2", "gwg"],
		body: skeleton(
			"Schulungsplan",
			"Pflichtschulungen je Funktion, Frequenz, Nachweis; Kompetenzmatrix.",
			[
				"Pflichtschulungen",
				"Zielgruppen und Frequenz",
				"Nachweis",
				"Auswertung",
			],
		),
	},
	{
		code: "RL-PHYSISCH",
		title: "Physische Sicherheit",
		type: "policy",
		domain: "physical",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 24,
		isoMandatory: false,
		controls: ["CC-PHY-01", "CC-PHY-02", "CC-PHY-03", "CC-PHY-05"],
		legalBasisRefs: ["ISO 27001 A.7"],
		frameworks: ["iso27001"],
		body: skeleton(
			"Physische Sicherheit",
			"Zonen, Zutritt, Arbeitsplätze, Versorgung, Entsorgung.",
			["Zonenkonzept", "Zutritt und Besucher", "Clean Desk", "Entsorgung"],
		),
	},
	{
		code: "VA-DOKUMENTENLENKUNG",
		title: "Verfahren Dokumentenlenkung",
		type: "procedure",
		domain: "governance",
		approverFunction: "compliance",
		reviewCycleMonths: 24,
		isoMandatory: true,
		controls: ["CC-GOV-08"],
		legalBasisRefs: ["ISO 27001 7.5", "MaRisk AT 5/6"],
		frameworks: ["iso27001"],
		body: skeleton(
			"Verfahren Dokumentenlenkung",
			"Nummernkreise, Versionen, Freigabe, Verteilung, Kenntnisnahme, Archivierung.",
			[
				"Dokumenttypen und Nummernkreise",
				"Erstellung und Freigabe",
				"Versionen",
				"Verteilung und Kenntnisnahme",
				"Archivierung",
			],
		),
	},
	{
		code: "VA-AUDITPROGRAMM",
		title: "Internes Auditprogramm",
		type: "plan",
		domain: "governance",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: true,
		controls: ["CC-GOV-06"],
		legalBasisRefs: ["ISO 27001 9.2", "DORA Art. 6(6)", "MaRisk BT 2"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Internes Auditprogramm",
			"Dreijahreszyklus, Umfang, Unabhängigkeit, Berichterstattung.",
			[
				"Zyklus und Umfang",
				"Auditor:innen und Unabhängigkeit",
				"Durchführung",
				"Berichte und Nachverfolgung",
			],
		),
	},
	{
		code: "BE-MANAGEMENTBEWERTUNG",
		title: "Protokoll Managementbewertung (Vorlage)",
		type: "template",
		domain: "governance",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: true,
		controls: ["CC-GOV-05"],
		legalBasisRefs: ["ISO 27001 9.3", "DORA Art. 6(5)"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Managementbewertung",
			"Inputs, Bewertung und Beschlüsse der obersten Leitung.",
			[
				"Status früherer Massnahmen",
				"Kontextänderungen",
				"Leistung (KPIs, Audits, Vorfälle)",
				"Risiken und Chancen",
				"Beschlüsse",
			],
		),
	},
	{
		code: "VA-ABWEICHUNGEN",
		title: "Verfahren Abweichungen und Korrekturmassnahmen",
		type: "procedure",
		domain: "governance",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 24,
		isoMandatory: true,
		controls: ["CC-GOV-07"],
		legalBasisRefs: ["ISO 27001 10.2", "DORA Art. 13"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Verfahren Abweichungen und Korrekturmassnahmen",
			"Erfassung, Ursachenanalyse, Korrektur, Wirksamkeitsprüfung.",
			["Quellen", "Ursachenanalyse", "Massnahmen", "Wirksamkeitsprüfung"],
		),
	},
	{
		code: "KZ-KOMMUNIKATION",
		title: "Kommunikationsmatrix",
		type: "concept",
		domain: "governance",
		approverFunction: "compliance",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-GOV-09"],
		legalBasisRefs: ["ISO 27001 7.4", "DORA Art. 14"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Kommunikationsmatrix",
			"Wer kommuniziert was, wann, an wen, über welchen Kanal — intern, Kunden, Partner, Behörden.",
			["Interne Kommunikation", "Kunden und Partner", "Behörden", "Krise"],
		),
	},
	{
		code: "RL-DATENSCHUTZ",
		title: "Datenschutzrichtlinie",
		type: "policy",
		domain: "compliance",
		approverFunction: "dpo",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-CMP-01"],
		legalBasisRefs: ["DSGVO Art. 5, 24, 32", "ISO 27001 A.5.34"],
		frameworks: ["dsgvo", "iso27001"],
		body: skeleton(
			"Datenschutzrichtlinie",
			"Grundsätze, Rollen, Verarbeitungsverzeichnis, Betroffenenrechte, Meldungen.",
			[
				"Grundsätze",
				"Rollen",
				"Verzeichnis und DSFA",
				"Betroffenenrechte",
				"Verletzungen",
			],
		),
	},
	{
		code: "RL-TESTPROGRAMM",
		title: "Testprogramm digitale operationale Resilienz",
		type: "plan",
		domain: "development",
		approverFunction: "ict_risk_function",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-TST-01", "CC-TST-02", "CC-DEV-04"],
		legalBasisRefs: ["DORA Art. 24–27", "NIS2 Art. 21(2)(f)"],
		frameworks: ["dora", "nis2"],
		body: skeleton(
			"Testprogramm digitale operationale Resilienz",
			"Jahresplan der Tests je kritischem System; Testarten, Tester, Nachverfolgung; TLPT falls benannt.",
			[
				"Umfang",
				"Testarten je System",
				"Tester und Unabhängigkeit",
				"Nachverfolgung",
				"TLPT",
			],
		),
	},
	{
		code: "RL-HINWEISGEBER",
		title: "Hinweisgeberkanal",
		type: "procedure",
		domain: "compliance",
		approverFunction: "compliance",
		reviewCycleMonths: 24,
		isoMandatory: false,
		controls: ["CC-INC-07"],
		legalBasisRefs: ["HinSchG", "GwG § 6 Abs. 5", "MiCAR Art. 116"],
		frameworks: ["gwg", "micar"],
		body: skeleton(
			"Hinweisgeberkanal",
			"Vertraulicher Meldekanal, Fristen (7 Tage Eingang, 3 Monate Rückmeldung), Schutz vor Repressalien.",
			["Kanal", "Bearbeitung und Fristen", "Vertraulichkeit", "Schutz"],
		),
	},
	{
		code: "KZ-NIS2-BETROFFENHEIT",
		title: "Betroffenheitsprüfung NIS2/BSIG",
		type: "record",
		domain: "compliance",
		approverFunction: "compliance",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-GOV-18"],
		legalBasisRefs: ["§ 28 BSIG", "§ 33 BSIG", "Art. 4 NIS2"],
		frameworks: ["nis2"],
		body: skeleton(
			"Betroffenheitsprüfung NIS2/BSIG",
			"Sektor, Grösse, lex specialis DORA, Anlage 1 Managed Services, Registrierung.",
			[
				"Sektor und Grösse",
				"Lex specialis",
				"Managed Services",
				"Ergebnis und Registrierung",
			],
		),
	},
	{
		code: "RL-ARBEITSANWEISUNG-RUNBOOKS",
		title: "Betriebshandbuch (Runbooks)",
		type: "manual",
		domain: "operations",
		approverFunction: "isb_ciso",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-OPS-08"],
		legalBasisRefs: ["ISO 27001 A.5.37"],
		frameworks: ["iso27001"],
		body: skeleton(
			"Betriebshandbuch",
			"Deploy, Backup/Restore, Rotation, Vorfallreaktion als erprobte Abläufe.",
			["Deploy", "Backup und Restore", "Schlüsselrotation", "Vorfallreaktion"],
		),
	},
	{
		code: "BE-ROLLEN",
		title: "Rollen- und Funktionsregister",
		type: "record",
		domain: "governance",
		approverFunction: "management_body",
		reviewCycleMonths: 12,
		isoMandatory: false,
		controls: ["CC-GOV-02", "CC-GOV-11", "CC-GOV-19"],
		legalBasisRefs: ["ISO 27001 5.3", "DORA Art. 5, 6(4)", "MaRisk AT 4.4"],
		frameworks: ["iso27001", "dora"],
		body: skeleton(
			"Rollen- und Funktionsregister",
			"Pflichtfunktionen mit Inhaber:in, Vertretung, Bestellung und Funktionstrennung.",
			["Pflichtfunktionen", "Vertretungen", "Funktionstrennung", "Nachweise"],
		),
	},
];

export const TEMPLATE_BY_CODE: ReadonlyMap<string, DocumentTemplate> = new Map(
	DOCUMENT_TEMPLATES.map((t) => [t.code, t]),
);
