import type { CatalogFrameworkMeta } from "./types";

// Rahmenwerk-Stammdaten (Rechtsstand Oktober 2026). Die Anforderungs-Indizes
// kommen je Phase dazu (P1: ISO/DORA/NIS2, P4: Finanz-Rahmenwerke, P5: Rest).
export const FRAMEWORKS: CatalogFrameworkMeta[] = [
	{
		slug: "iso27001",
		name: "ISO/IEC 27001:2022",
		version: "2022",
		authority: "ISO/IEC",
		jurisdiction: "global",
		description:
			"Managementsystem für Informationssicherheit (Klauseln 4–10) und 93 Annex-A-Controls. Freiwillig, aber das beste Gerüst, um DORA-Nachweise zu bündeln.",
		recommendedApproach:
			"Zuerst zertifizieren, dann das DORA-Delta schließen — rund zwei Drittel der DORA-Kapitel-II-Nachweise sind damit erledigt.",
		sourceUrl: "https://www.iso.org/standard/27001",
		sortOrder: 10,
		phase: "P1",
	},
	{
		slug: "dora",
		name: "DORA — Digital Operational Resilience Act",
		version: "VO (EU) 2022/2554",
		authority: "EU / BaFin",
		jurisdiction: "eu",
		legalBasis: "Verordnung (EU) 2022/2554",
		legalBasisRefs: [
			"RTS 2024/1774",
			"RTS 2024/1772",
			"RTS 2025/301",
			"ITS 2025/302",
			"RTS 2024/1773",
			"ITS 2024/2956",
			"RTS 2025/532",
			"RTS 2025/1190",
		],
		description:
			"Seit 17.01.2025 unmittelbar geltender IKT-Pflichtenkatalog für Zahlungsinstitute, E-Geld-Institute und CASPs: Risikomanagement, Vorfälle, Tests, Drittparteien, Informationsaustausch.",
		sourceUrl: "https://eur-lex.europa.eu/eli/reg/2022/2554/oj",
		sortOrder: 20,
		phase: "P1",
	},
	{
		slug: "nis2",
		name: "NIS2 / BSIG",
		version: "RL (EU) 2022/2555 · NIS2UmsuCG",
		authority: "EU / BSI",
		jurisdiction: "de",
		legalBasis: "Richtlinie (EU) 2022/2555; BSIG",
		description:
			"Cybersicherheitspflichten für wichtige und besonders wichtige Einrichtungen. Für DORA-Finanzunternehmen gilt DORA als lex specialis (§ 28 Abs. 6 BSIG) — es bleiben Betroffenheitsprüfung und Registrierung (§ 33 BSIG).",
		sourceUrl: "https://eur-lex.europa.eu/eli/dir/2022/2555/oj",
		sortOrder: 30,
		phase: "P1",
	},
	{
		slug: "micar",
		name: "MiCAR + KMAG",
		version: "VO (EU) 2023/1114",
		authority: "EU / BaFin",
		jurisdiction: "eu",
		legalBasis: "Verordnung (EU) 2023/1114; Kryptomärkteaufsichtsgesetz",
		legalBasisRefs: [
			"DelVO 2025/305",
			"DelVO 2025/299",
			"DelVO 2025/1140",
			"DelVO 2025/1141",
			"DelVO 2025/1142",
			"DelVO 2025/414",
		],
		description:
			"Zulassung und Pflichten von Kryptowerte-Dienstleistern (Titel V), Token-Emission (Titel II–IV), Marktmissbrauch (Titel VI).",
		sourceUrl: "https://eur-lex.europa.eu/eli/reg/2023/1114/oj",
		sortOrder: 40,
		appliesFromStage: "1_agent",
		phase: "P4",
	},
	{
		slug: "zag",
		name: "ZAG / PSD2",
		version: "ZAG; RL (EU) 2015/2366; RTS (EU) 2018/389",
		authority: "BaFin / Bundesbank",
		jurisdiction: "de",
		legalBasis: "Zahlungsdiensteaufsichtsgesetz",
		description:
			"Erlaubnis, Kapital, Kundengeldsicherung, Organisation, Anzeigen, Meldungen, starke Kundenauthentifizierung. IT- und Vorfallthemen seit 2025 über DORA.",
		sourceUrl: "https://www.gesetze-im-internet.de/zag_2018/",
		sortOrder: 50,
		appliesFromStage: "1_agent",
		phase: "P4",
	},
	{
		slug: "zag-marisk",
		name: "ZAG-MaRisk",
		version: "BaFin-Rundschreiben 07/2024",
		authority: "BaFin",
		jurisdiction: "de",
		legalBasis: "§ 27 ZAG",
		description:
			"Mindestanforderungen an das Risikomanagement von Zahlungs- und E-Geld-Instituten (AT/BT). Schlanker als die Bank-MaRisk; BAIT/ZAIT entfallen für DORA-Institute.",
		sortOrder: 60,
		appliesFromStage: "2_casp_zag",
		phase: "P4",
	},
	{
		slug: "gwg",
		name: "GwG (Geldwäschegesetz)",
		version: "GwG + GwGMeldV",
		authority: "BaFin / FIU",
		jurisdiction: "de",
		legalBasis: "Geldwäschegesetz",
		description:
			"Risikoanalyse, interne Sicherungsmaßnahmen, Sorgfaltspflichten, Verdachtsmeldungen, Aufbewahrung. Große Teile werden am 10.07.2027 von der AMLR verdrängt.",
		sourceUrl: "https://www.gesetze-im-internet.de/gwg_2017/",
		successorSlug: "amlr",
		sortOrder: 70,
		phase: "P4",
	},
	{
		slug: "amlr",
		name: "AMLR — EU-Geldwäscheverordnung",
		version: "VO (EU) 2024/1624",
		authority: "EU / AMLA",
		jurisdiction: "eu",
		legalBasis: "Verordnung (EU) 2024/1624; AMLD6",
		description:
			"Unmittelbar geltendes EU-Geldwäscherecht ab 10.07.2027: harmonisierte Sorgfaltspflichten, Compliance-Manager in der Leitung, Krypto-Korrespondenzbeziehungen, Self-hosted-Adressen.",
		sourceUrl: "https://eur-lex.europa.eu/eli/reg/2024/1624/oj",
		sortOrder: 80,
		phase: "P4",
	},
	{
		slug: "tfr",
		name: "Geldtransferverordnung (Travel Rule)",
		version: "VO (EU) 2023/1113",
		authority: "EU / BaFin",
		jurisdiction: "eu",
		legalBasis: "Verordnung (EU) 2023/1113; EBA/GL/2024/11",
		description:
			"Begleitdaten bei Geld- und Kryptowertetransfers: Originator/Begünstigter ohne Schwellenwert, Self-hosted-Adressen ab 1.000 €, Aufbewahrung 5 Jahre.",
		sourceUrl: "https://eur-lex.europa.eu/eli/reg/2023/1113/oj",
		sortOrder: 90,
		phase: "P4",
	},
	{
		slug: "sanctions",
		name: "Sanktionsrecht (EU / AWG / OFAC)",
		authority: "EU / Bundesbank / BAFA",
		jurisdiction: "eu",
		legalBasis: "VO (EU) 833/2014; AWG § 18; FATF-Listen",
		description:
			"Listenabgleich, Hochrisikoländer, Embargos — täglich automatisiert, nachgewiesen.",
		sortOrder: 100,
		phase: "P4",
	},
	{
		slug: "dsgvo",
		name: "DSGVO / BDSG",
		version: "VO (EU) 2016/679",
		authority: "EU / Datenschutzaufsicht",
		jurisdiction: "eu",
		legalBasis: "Verordnung (EU) 2016/679; BDSG",
		description:
			"Verarbeitungsverzeichnis, Rechtsgrundlagen, TOMs, Meldung von Datenpannen, DSFA, Betroffenenrechte.",
		sourceUrl: "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
		sortOrder: 110,
		phase: "P5",
	},
	{
		slug: "dac8",
		name: "DAC8 (KStTG)",
		version: "KStTG",
		authority: "BZSt",
		jurisdiction: "de",
		legalBasis: "Kryptowerte-Steuertransparenzgesetz",
		description:
			"Steuerliche Meldepflichten für Kryptowerte-Dienstleister, Erstmeldung 31.07.2027.",
		sortOrder: 120,
		appliesFromStage: "2_casp_zag",
		phase: "P4",
	},
	{
		slug: "awv",
		name: "AWV / Zahlungsverkehrsstatistik",
		authority: "Bundesbank",
		jurisdiction: "de",
		legalBasis: "AWV § 67; FinDAG § 16",
		description:
			"Meldungen im Außenwirtschaftsverkehr und Zahlungsverkehrsstatistik.",
		sortOrder: 130,
		appliesFromStage: "2_casp_zag",
		phase: "P4",
	},
	{
		slug: "kassen",
		name: "Kassenrecht (KassenSichV / GoBD)",
		authority: "BMF",
		jurisdiction: "de",
		legalBasis: "KassenSichV; § 146a AO; DSFinV-K; GoBD",
		description:
			"Produkt-Anforderungen an die Händlerkasse (TSE, DSFinV-K-Export, Belegausgabe).",
		sortOrder: 140,
		phase: "P4",
	},
	{
		slug: "kwg",
		name: "KWG / Banken-MaRisk",
		authority: "BaFin / EZB",
		jurisdiction: "de",
		legalBasis: "Kreditwesengesetz; MaRisk; CRD VI",
		description:
			"Erlaubnis und laufende Pflichten eines CRR-Instituts — erst mit Lizenzstufe 4 relevant.",
		sortOrder: 150,
		appliesFromStage: "4_bank",
		phase: "P5",
	},
];

export const FRAMEWORK_SLUGS = FRAMEWORKS.map((f) => f.slug);
